import { Prisma } from "@/src/generated/prisma/client";
import { z } from "zod";
import type {
  ProjectFactCategory,
  ProjectFactDraft,
  ProjectKnowledgeCitation,
} from "@/src/domain/project-chat";
import type { JsonSchemaObject } from "@/src/lib/llm-json-schemas";
import { StructuredOutputError } from "@/src/lib/bedrock-structured-llm-client";
import { resolveWorkbaseLlmProvider } from "@/src/lib/llm-config";
import { prisma } from "@/src/lib/prisma";
import { normalizeWhitespace } from "@/src/lib/utils";
import { getBedrockStructuredLlmClient } from "@/src/services/bedrock-runtime";
import {
  buildProjectFactEmbeddingText,
  upsertProjectFactEmbedding,
} from "@/src/services/knowledge-embedding-service";
import { promoteRepositoryCitations } from "@/src/services/repository-evidence-promotion-service";
import { recordChange } from "@/src/services/knowledge-reconciliation-service";

const categorySchema = z.enum([
  "architecture",
  "behavior",
  "data_flow",
  "code_location",
  "dependency",
  "configuration",
]);
const factExtractionSchema = z.object({
  facts: z.array(z.object({
    statement: z.string().trim().min(10).max(500),
    category: categorySchema,
    confidence: z.enum(["low", "medium", "high"]),
    sensitivityFlag: z.boolean(),
    reviewNotes: z.string().trim().max(1_000).nullable(),
    citationIndexes: z.array(z.number().int().min(1)).min(1).max(4),
  })).max(8),
  coverageGaps: z.array(z.string().trim().min(2).max(500)).max(6),
});

const factExtractionJsonSchema: JsonSchemaObject = {
  type: "object",
  additionalProperties: false,
  required: ["facts", "coverageGaps"],
  properties: {
    facts: {
      type: "array",
      maxItems: 8,
      items: {
        type: "object",
        additionalProperties: false,
        required: [
          "statement",
          "category",
          "confidence",
          "sensitivityFlag",
          "reviewNotes",
          "citationIndexes",
        ],
        properties: {
          statement: { type: "string", minLength: 10, maxLength: 500 },
          category: { type: "string", enum: categorySchema.options },
          confidence: { type: "string", enum: ["low", "medium", "high"] },
          sensitivityFlag: { type: "boolean" },
          reviewNotes: { anyOf: [{ type: "string", maxLength: 1_000 }, { type: "null" }] },
          citationIndexes: {
            type: "array",
            minItems: 1,
            maxItems: 4,
            items: { type: "integer", minimum: 1 },
          },
        },
      },
    },
    coverageGaps: {
      type: "array",
      maxItems: 6,
      items: { type: "string", minLength: 2, maxLength: 500 },
    },
  },
};

function toInputJson(value: unknown): Prisma.InputJsonValue {
  return JSON.parse(JSON.stringify(value)) as Prisma.InputJsonValue;
}

function tokens(value: string) {
  return new Set(
    normalizeWhitespace(value.toLowerCase())
      .split(/[^a-z0-9_./-]+/)
      .filter((token) => token.length > 2),
  );
}

function similarity(left: string, right: string) {
  const leftTokens = tokens(left);
  const rightTokens = tokens(right);
  if (!leftTokens.size || !rightTokens.size) return 0;
  const intersection = Array.from(leftTokens).filter((token) => rightTokens.has(token)).length;
  return intersection / new Set([...leftTokens, ...rightTokens]).size;
}

function mockFacts(citations: readonly ProjectKnowledgeCitation[]): ProjectFactDraft[] {
  const citation = citations.find((entry) => entry.kind === "github_file");
  if (!citation) return [];
  return [{
    statement: `${citation.path ?? citation.label} contains repository evidence relevant to the requested architecture question.`,
    category: "architecture",
    confidence: "medium",
    sensitivityFlag: false,
    reviewNotes: "Generated by the mock project-fact extractor.",
    citationIndexes: [citations.indexOf(citation) + 1],
  }];
}

async function extractFacts(input: {
  question: string;
  workItemTitle: string;
  citations: readonly ProjectKnowledgeCitation[];
  partial: boolean;
  maxFacts: number;
}) {
  if (resolveWorkbaseLlmProvider() === "mock") {
    return { facts: mockFacts(input.citations), coverageGaps: [], tokenUsage: null };
  }

  const result = await getBedrockStructuredLlmClient().generateStructured({
    systemPrompt: [
      "You extract reviewable technical project facts from immutable repository excerpts.",
      "Each fact must be directly supported by its cited excerpts and must not claim user ownership or production impact.",
      "Prefer reusable architecture, behavior, data-flow, code-location, dependency, or configuration facts.",
      "Return no fact when the excerpt does not support a useful statement.",
    ].join(" "),
    userPrompt: JSON.stringify({
      project: input.workItemTitle,
      question: input.question,
      partialResearch: input.partial,
      maximumFacts: input.maxFacts,
      excerpts: input.citations.map((citation, index) => ({
        citationIndex: index + 1,
        repository: citation.repository,
        commitSha: citation.commitSha,
        path: citation.path,
        lines: citation.startLine && citation.endLine
          ? `${citation.startLine}-${citation.endLine}`
          : null,
        excerpt: citation.excerpt,
      })),
    }),
    schema: factExtractionSchema,
    schemaName: "project_fact_candidates",
    schemaDescription: "Grounded technical project facts and remaining coverage gaps.",
    jsonSchema: factExtractionJsonSchema,
    maxTokens: 8_000,
    temperature: 0,
    effort: "high",
  });
  return { ...result.data, tokenUsage: result.tokenUsage };
}

export async function extractFactsWithRecovery(input: Parameters<typeof extractFacts>[0]) {
  try {
    return await extractFacts(input);
  } catch (error) {
    if (!(error instanceof StructuredOutputError) || error.status === "provider_error") throw error;

    const recoveredFacts: z.infer<typeof factExtractionSchema>["facts"] = [];
    const coverageGaps = [
      "The full fact-extraction response exceeded or failed its structured-output contract; Workbase retried smaller excerpt batches.",
    ];
    const recoveryUsage: unknown[] = [{ phase: "full_extraction", usage: error.tokenUsage, status: error.status }];
    for (let offset = 0; offset < input.citations.length && recoveredFacts.length < input.maxFacts; offset += 4) {
      const citations = input.citations.slice(offset, offset + 4);
      try {
        const recovered = await extractFacts({
          ...input,
          citations,
          partial: true,
          maxFacts: input.maxFacts - recoveredFacts.length,
        });
        recoveredFacts.push(...recovered.facts.map((fact) => ({
          ...fact,
          reviewNotes: fact.reviewNotes ?? null,
          citationIndexes: fact.citationIndexes.map((index) => index + offset),
        })));
        coverageGaps.push(...recovered.coverageGaps);
        recoveryUsage.push({ phase: `batch_${Math.floor(offset / 4) + 1}`, usage: recovered.tokenUsage, status: "success" });
      } catch (batchError) {
        recoveryUsage.push({
          phase: `batch_${Math.floor(offset / 4) + 1}`,
          usage: batchError instanceof StructuredOutputError ? batchError.tokenUsage : null,
          status: "failed",
        });
      }
    }
    if (!recoveredFacts.length) throw error;
    return {
      facts: recoveredFacts.slice(0, input.maxFacts),
      coverageGaps: Array.from(new Set(coverageGaps)),
      tokenUsage: recoveryUsage,
    };
  }
}

export async function createProjectFactCandidates(input: {
  runId: string;
  userId: string;
  workItemId: string;
  question: string;
  citations: readonly ProjectKnowledgeCitation[];
  partial: boolean;
  batchNumber?: number;
  maxFacts?: number;
}) {
  const existingCandidates = await prisma.agentRunCandidate.findMany({
    where: {
      agentRunId: input.runId,
      kind: { in: ["new_project_fact", "project_fact_revision"] },
    },
    select: { id: true, projectFactId: true, status: true },
  });
  if (existingCandidates.length) {
    return {
      candidateIds: existingCandidates.map((candidate) => candidate.id),
      activeProjectFactIds: existingCandidates.flatMap((candidate) =>
        candidate.status === "approved" && candidate.projectFactId ? [candidate.projectFactId] : [],
      ),
      coverageGaps: [],
      tokenUsage: null,
    };
  }

  const workItem = await prisma.workItem.findFirstOrThrow({
    where: { id: input.workItemId, userId: input.userId },
    select: { title: true },
  });
  const repositoryCitations = input.citations.filter((citation) => citation.kind === "github_file");
  if (!repositoryCitations.length) return { candidateIds: [], activeProjectFactIds: [], coverageGaps: [], tokenUsage: null };
  const extracted = await extractFactsWithRecovery({
    question: input.question,
    workItemTitle: workItem.title,
    citations: repositoryCitations,
    partial: input.partial,
    maxFacts: Math.min(8, Math.max(1, input.maxFacts ?? 4)),
  });
  const validFacts = extracted.facts.flatMap((fact) => {
    const citationIndexes = Array.from(new Set(fact.citationIndexes))
      .filter((index) => index >= 1 && index <= repositoryCitations.length);
    return citationIndexes.length ? [{ ...fact, citationIndexes }] : [];
  }).slice(0, Math.min(8, Math.max(1, input.maxFacts ?? 4)));
  if (!validFacts.length) {
    return { candidateIds: [], activeProjectFactIds: [], coverageGaps: extracted.coverageGaps, tokenUsage: extracted.tokenUsage };
  }

  const selectedOriginalIndexes = Array.from(
    new Set(validFacts.flatMap((fact) => fact.citationIndexes.map((index) => index - 1))),
  );
  const selectedCitations = selectedOriginalIndexes.map((index) => repositoryCitations[index]!);
  const promoted = await promoteRepositoryCitations({
    workItemId: input.workItemId,
    citations: selectedCitations,
    reviewScope: `project-fact-research:${input.runId}`,
  });
  const localIndexByOriginal = new Map(
    selectedOriginalIndexes.map((originalIndex, localIndex) => [originalIndex, localIndex]),
  );
  const existingFacts = await prisma.projectFact.findMany({
    where: { workItemId: input.workItemId, status: "approved" },
    include: { evidence: { include: { evidenceItem: { select: { metadata: true } } } } },
    orderBy: { updatedAt: "desc" },
  });
  const batchNumber = input.batchNumber ?? 1;
  const created: Array<{ candidateId: string; projectFactId: string; statement: string; category: ProjectFactCategory; reviewNotes: string | null; autoSafe: boolean }> = [];

  await prisma.$transaction(async (tx) => {
    for (const fact of validFacts) {
      const ranked = existingFacts
        .map((existing) => ({ existing, score: similarity(fact.statement, existing.statement) }))
        .sort((left, right) => right.score - left.score);
      const closest = ranked[0] ?? null;
      const citedShas = new Set(fact.citationIndexes.flatMap((oneBasedIndex) => {
        const citation = repositoryCitations[oneBasedIndex - 1];
        return citation?.commitSha ? [citation.commitSha] : [];
      }));
      const closestEvidenceShas = new Set(closest?.existing.evidence.flatMap((entry) => {
        const metadata = entry.evidenceItem.metadata;
        if (!metadata || typeof metadata !== "object" || Array.isArray(metadata)) return [];
        const commitSha = (metadata as Record<string, unknown>).commitSha;
        return typeof commitSha === "string" ? [commitSha] : [];
      }) ?? []);
      const alreadyGroundedAtRevision =
        (closest?.score ?? 0) >= 0.86 &&
        citedShas.size > 0 &&
        Array.from(citedShas).every((sha) => closestEvidenceShas.has(sha));
      if (alreadyGroundedAtRevision) continue;
      const supersedes = (closest?.score ?? 0) >= 0.86
        ? closest!.existing
        : ranked.find(
            (entry) => entry.existing.category === fact.category && entry.score >= 0.42,
          )?.existing ?? null;
      const evidenceIds = fact.citationIndexes.flatMap((oneBasedIndex) => {
        const localIndex = localIndexByOriginal.get(oneBasedIndex - 1);
        if (localIndex == null) return [];
        const evidenceId = promoted.evidenceIdByCitationIndex.get(localIndex);
        return evidenceId ? [evidenceId] : [];
      });
      if (!evidenceIds.length) continue;
      const autoSafe = !fact.sensitivityFlag && fact.confidence !== "low";
      const projectFact = await tx.projectFact.create({
        data: {
          workItemId: input.workItemId,
          statement: fact.statement,
          category: fact.category,
          confidence: fact.confidence,
          status: autoSafe ? "approved" : "draft",
          sensitivityFlag: fact.sensitivityFlag,
          reviewNotes: fact.reviewNotes,
          searchText: normalizeWhitespace([fact.statement, fact.category, fact.reviewNotes ?? ""].join(" ")),
          supersedesProjectFactId: supersedes?.id ?? null,
          lifecycleStatus: autoSafe ? "active" : "quarantined",
          reviewState: "pending_review",
          approvalSource: "automation",
          autoAppliedAt: autoSafe ? new Date() : null,
          validatedThroughSha: Array.from(citedShas)[0] ?? null,
          lastValidatedAt: new Date(),
          evidence: {
            create: evidenceIds.map((evidenceItemId) => ({ evidenceItemId })),
          },
        },
      });
      const candidate = await tx.agentRunCandidate.create({
        data: {
          agentRunId: input.runId,
          projectFactId: projectFact.id,
          kind: supersedes ? "project_fact_revision" : "new_project_fact",
          status: autoSafe ? "approved" : "pending",
          batchNumber,
          ordinal: created.length + 1,
          snapshot: toInputJson({
            statement: fact.statement,
            category: fact.category,
            confidence: fact.confidence,
            sensitivityFlag: fact.sensitivityFlag,
            reviewNotes: fact.reviewNotes,
            evidenceIds,
            evidenceLabels: evidenceIds.map((id) => id),
            partial: input.partial,
            supersedesProjectFactId: supersedes?.id ?? null,
          }),
          reviewedAt: autoSafe ? new Date() : null,
        },
      });
      if (autoSafe && supersedes) {
        await tx.projectFact.updateMany({
          where: { id: supersedes.id, status: "approved", lifecycleStatus: "active" },
          data: { status: "superseded", lifecycleStatus: "superseded" },
        });
      }
      if (autoSafe) {
        await tx.evidenceItem.updateMany({
          where: { id: { in: evidenceIds } },
          data: {
            included: true,
            lifecycleStatus: "active",
            reviewState: "pending_review",
            approvalSource: "automation",
            autoAppliedAt: new Date(),
          },
        });
      }
      created.push({
        candidateId: candidate.id,
        projectFactId: projectFact.id,
        statement: fact.statement,
        category: fact.category,
        reviewNotes: fact.reviewNotes ?? null,
        autoSafe,
      });
    }
  });

  await Promise.allSettled(created.map((entry) => upsertProjectFactEmbedding({
    projectFactId: entry.projectFactId,
    inputText: buildProjectFactEmbeddingText(entry),
  })));
  await Promise.allSettled(created.map((entry) => recordChange({
    workItemId: input.workItemId,
    entityKind: "project_fact",
    action: entry.autoSafe ? "created" : "quarantined",
    entityId: entry.projectFactId,
    afterSnapshot: { statement: entry.statement, category: entry.category, lifecycleStatus: entry.autoSafe ? "active" : "quarantined" },
    reason: entry.autoSafe
      ? "Repository research auto-applied a supported Project Fact for later review."
      : "Repository research quarantined a Project Fact that failed the automatic safety gate.",
    provenance: { agentRunId: input.runId },
    suffix: `${input.runId}:${entry.projectFactId}`,
  })));
  if (!created.length && promoted.newIds.length) {
    await prisma.evidenceItem.deleteMany({
      where: { id: { in: promoted.newIds }, type: "github_file_excerpt", included: false },
    });
  }

  return {
    candidateIds: created.map((entry) => entry.candidateId),
    activeProjectFactIds: created.filter((entry) => entry.autoSafe).map((entry) => entry.projectFactId),
    coverageGaps: extracted.coverageGaps,
    tokenUsage: extracted.tokenUsage,
  };
}
