import { generateClaimsAction } from "@/app/actions";
import { Badge } from "@/components/ui/badge";
import { SubmitButton } from "@/components/forms/submit-button";
import { ClaimCard } from "@/components/claims/claim-card";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { PageHeader, WorkbaseFrame } from "@/components/workbase-frame";
import { getWorkItemForUser } from "@/src/data/workbase";
import { getDemoUser } from "@/src/lib/demo-user";

export const dynamic = "force-dynamic";

export default async function ClaimReviewPage({
  params,
  searchParams,
}: {
  params: Promise<{ id: string }>;
  searchParams: Promise<{ error?: string; result?: string }>;
}) {
  const { id } = await params;
  const { error, result } = await searchParams;
  const user = await getDemoUser();
  const workItem = await getWorkItemForUser(user.id, id);
  const generateClaims = generateClaimsAction.bind(null, workItem.id);

  const approved = workItem.claims.filter(
    (claim) => claim.verificationStatus === "approved",
  ).length;
  const flagged = workItem.claims.filter(
    (claim) => claim.verificationStatus === "flagged",
  ).length;
  const pendingClaims = workItem.claims.filter(
    (claim) =>
      claim.verificationStatus === "draft" || claim.verificationStatus === "flagged",
  );
  const approvedClaims = workItem.claims.filter(
    (claim) => claim.verificationStatus === "approved",
  );
  const rejectedClaims = workItem.claims.filter(
    (claim) => claim.verificationStatus === "rejected",
  );

  return (
    <WorkbaseFrame>
      <PageHeader
        eyebrow="Claim review"
        title={`Review claims for ${workItem.title}`}
        description="This is the core Workbase surface. Every claim stays grounded in evidence, rationale, risk, visibility, and sensitivity before it can feed an artifact."
        actions={
          <form action={generateClaims}>
            <SubmitButton pendingLabel="Refreshing claims..." variant="secondary">
              Regenerate pending claims
            </SubmitButton>
          </form>
        }
      />

      <section className="grid gap-4 lg:grid-cols-3">
        <Card>
          <CardHeader>
            <CardTitle>Total claims</CardTitle>
          </CardHeader>
          <CardContent>
            <p className="font-display text-4xl font-semibold tracking-[-0.05em] text-[color:var(--ink-strong)]">
              {workItem.claims.length}
            </p>
          </CardContent>
        </Card>
        <Card>
          <CardHeader>
            <CardTitle>Approved</CardTitle>
            <CardDescription>Eligible for artifacts when visibility also matches.</CardDescription>
          </CardHeader>
          <CardContent>
            <p className="font-display text-4xl font-semibold tracking-[-0.05em] text-[color:var(--ink-strong)]">
              {approved}
            </p>
          </CardContent>
        </Card>
        <Card>
          <CardHeader>
            <CardTitle>Flagged</CardTitle>
            <CardDescription>Claims needing caution on wording or sensitivity.</CardDescription>
          </CardHeader>
          <CardContent>
            <p className="font-display text-4xl font-semibold tracking-[-0.05em] text-[color:var(--ink-strong)]">
              {flagged}
            </p>
          </CardContent>
        </Card>
      </section>

      {error === "invalid-claim" ? (
        <Card className="border-amber-200 bg-amber-50 shadow-none">
          <CardContent className="py-4">
            <p className="text-sm leading-6 text-amber-900">
              Workbase could not save that claim. The current form data did not pass validation.
              This was previously caused by autogenerated review notes being too long.
            </p>
          </CardContent>
        </Card>
      ) : null}

      {result ? (
        <Card className="border-emerald-200 bg-emerald-50 shadow-none">
          <CardContent className="py-4">
            <p className="text-sm leading-6 text-emerald-900">
              {result === "approved"
                ? "Claim approved. It has moved into the approved section."
                : result === "rejected"
                  ? "Claim rejected. It has moved into the rejected section."
                  : "Claim changes saved."}
            </p>
          </CardContent>
        </Card>
      ) : null}

      <section className="grid gap-4">
        {workItem.claims.length ? (
          <>
            <Card className="border-cyan-200 bg-cyan-50 shadow-none">
              <CardHeader>
                <div className="flex flex-wrap items-center gap-2">
                  <CardTitle>Pending review</CardTitle>
                  <Badge tone="warning">{pendingClaims.length} claims</Badge>
                </div>
                <CardDescription>
                  These are the claims that still need a decision.
                </CardDescription>
              </CardHeader>
            </Card>
            {pendingClaims.length ? (
              pendingClaims.map((claim) => (
                <ClaimCard
                  key={claim.id}
                  claim={{
                    ...claim,
                    workItemId: workItem.id,
                  }}
                />
              ))
            ) : (
              <Card>
                <CardContent className="py-6">
                  <p className="text-sm leading-6 text-[color:var(--ink-soft)]">
                    No pending claims right now.
                  </p>
                </CardContent>
              </Card>
            )}

            <Card className="border-emerald-200 bg-emerald-50 shadow-none">
              <CardHeader>
                <div className="flex flex-wrap items-center gap-2">
                  <CardTitle>Approved</CardTitle>
                  <Badge tone="success">{approvedClaims.length} claims</Badge>
                </div>
                <CardDescription>
                  Approved claims feed Artifact generation when visibility allows it.
                </CardDescription>
              </CardHeader>
            </Card>
            {approvedClaims.length ? (
              approvedClaims.map((claim) => (
                <ClaimCard
                  key={claim.id}
                  claim={{
                    ...claim,
                    workItemId: workItem.id,
                  }}
                />
              ))
            ) : null}

            {rejectedClaims.length ? (
              <>
                <Card className="border-rose-200 bg-rose-50 shadow-none">
                  <CardHeader>
                    <div className="flex flex-wrap items-center gap-2">
                      <CardTitle>Rejected</CardTitle>
                      <Badge tone="danger">{rejectedClaims.length} claims</Badge>
                    </div>
                    <CardDescription>
                      Rejected claims stay persisted for auditability, but they are excluded from artifacts.
                    </CardDescription>
                  </CardHeader>
                </Card>
                {rejectedClaims.map((claim) => (
                  <ClaimCard
                    key={claim.id}
                    claim={{
                      ...claim,
                      workItemId: workItem.id,
                    }}
                  />
                ))}
              </>
            ) : null}
          </>
        ) : (
          <Card>
            <CardHeader>
              <CardTitle>No claims yet</CardTitle>
              <CardDescription>
                Generate candidate claims from the attached sources before starting review.
              </CardDescription>
            </CardHeader>
            <CardContent>
              <form action={generateClaims}>
                <SubmitButton pendingLabel="Generating claims...">
                  Generate candidate claims
                </SubmitButton>
              </form>
            </CardContent>
          </Card>
        )}
      </section>
    </WorkbaseFrame>
  );
}
